#!/bin/sh

fail () {
    echo "$@"
    exit 1
}

REV=$(python -c 'import pyinstall; print pyinstall.get_svn_revision(".")')
FILE="Deliverance-snapshot-r${REV}.pybundle"

if [ -e "$FILE" ] ; then
    echo "Bundle file $FILE already exists"
    exit 0
fi

echo "CREATING BUNDLE: $FILE"
echo

pyinstall.py --bundle=$FILE --build=build-bundle-files/ --src=src-bundle-files/ \
  -e svn+http://codespeak.net/svn/z3/deliverance/sandbox/ianb/deliverance/trunk#egg=Deliverance \
  || fail 'Bundle failed'

echo 'INSTALLING'
echo

rm -rf TEST
pyinstall.py -E TEST Deliverance.pybundle \
  || fail 'Install failed'

cd TEST/src/deliverance
chmod +x test
./test \
  || fail 'Tests failed'

