#!/bin/sh

fail () {
    echo "$@"
    exit 1
}

if [ "$1" = "upload" ] ; then
    shift
    FILENAME="$1"
    if [ -z "$FILENAME" ] ; then
        echo "Usage: `basename $0` uplaod FILENAME"
        exit 2
    fi
    cat $FILENAME | ssh flow.openplans.org "ssh acura.openplans.org \"cd /www/deliverance.openplans.org/dist/ ; cat > $FILENAME ; rm Deliverance-snapshot-latest.pybundle ; ln -s $FILENAME Deliverance-snapshot-latest.pybundle\""
    exit
fi

REV=$(python -c 'import pyinstall; print pyinstall.get_svn_revision(".")')
FILE="Deliverance-snapshot-r${REV}.pybundle"

if [ -e "$FILE" ] ; then
    echo "Bundle file $FILE already exists"
    exit 0
fi

echo "CREATING BUNDLE: $FILE"
echo

## FIXME: httplib2 still isn't being included
## httplib2 location is a temporary problem with a bad pypi entry
pyinstall.py --bundle=$FILE --build=build-bundle-files/ --src=src-bundle-files/ \
  -f http://httplib2.googlecode.com/files/httplib2-0.4.0.tar.gz#egg=httplib2-0.4.0 \
  http://httplib2.googlecode.com/svn/trunk/#egg=httplib2 \
  http://codespeak.net/svn/z3/deliverance/trunk#egg=Deliverance \
  supervisor PasteScript \
  http://svn.colorstudy.com/home/ianb/PageCollector/trunk#egg=PageCollector \
  || fail 'Bundle failed'

echo 'INSTALLING'
echo

rm -rf TEST
pyinstall.py -E TEST $FILE \
  || fail 'Install failed'

cd TEST/src/deliverance
chmod +x test
./test \
  || fail 'Tests failed'

